[[questions]]
q = "综合评价本次游戏的话，哪一条比较符合你的看法?"
options = [
"很喜欢，期待能有更多这类游戏出现",
"全新的体验，感觉很有趣",
"还算有点意思，不过没有惊艳的感觉",
"虽然很新奇，但很多时候是迷茫的",
"我完全不知道自己在做什么"
]
[[questions]]
q = "关于游戏的场景，哪一条比较符合你的看法？"
options = [
"场景非常华丽，能让我完全沉浸其中",
"场景比较不错，有一定代入感",
"没亮点，但也不影响游戏进行",
"装饰脏旧，道具有一些损毁，让人不舒服",
"装饰落后，道具破损严重，玩的十分不流畅"
]
[[questions]]
q = "关于激光，哪一条比较符合你的看法？"
options = [
"就像真的有人来追我一样，让我感到非常刺激",
"科技感很强，激光的效果很新颖",
"中规中矩，没出乎意料，不能说是亮点",
"没什么特别的感觉，我明知它没有危险",
"完全不知道它存在的意义"
]
[[questions]]
q = "关于这样的运动类游戏，哪一条比较符合你的看法？"
options = [
"感觉很好，非常紧张和刺激",
"比较有趣，但时间太短了",
"有些累人，不太适合女性",
"细节瑕疵不少，都能改善的话应该会好玩",
"无法让我享受到乐趣，没前途的游戏类型"
]
[[questions]]
q = "关于我们的服务质量，哪一条比较符合你的看法？"
options = [
"态度很好，让我们在游戏前的准备很充足",
"还不错，解决了一些疑惑",
"一般吧，没太在意服务员",
"感觉不够专业，不知道在讲什么",
"服务态度比较差，让我很不舒服"
]
[[questions]]
q = "你是从哪个渠道知道的这款游戏？"
options = [
"我关注了微信公众号",
"从微信朋友圈的转发看到",
"官方微博或者微博朋友转发的",
"是朋友选的游戏",
"其他渠道看到的，慕名而来"
]
